spring:
  datasource:
    username: root
    password: cagatay123
    url: jdbc:mysql://localhost:3306/basketballteamdb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true